### ISSUE TITLE
Strange tabstop detection in go

### ISSUE THREAD

**Issue by lutzky** [tpope/vim-sleuth#28]
This plugin will, for whatever reason, detect `ts=8` for the following `go` file, when `ts=2` for go in my settings:

```go
package lutzky

const k = `
multiline
  interestingline1
`

func main() {
  interestingline2 := 5
}
```

Note that this file is formatted by `gofmt`. `interestingline1` is manually indented by 2 spaces, whereas `intererestingline2` is `gofmt`-indented by a tab.

This might be a super-weird edge case, feel free to close as WONTFIX. (I'll be referencing this issue in another one)

**Comment by tpope** [comment]
If you mix tabs and spaces it assumes you are using tabs as a stand in for 8 spaces. This is an old but popular convention; it can be found all over Vim's runtime files for instance.

I would entertain a fix similar to [the python docstring exception](https://github.com/tpope/vim-sleuth/blob/1db371f776215ab0d1c49c9780e008a6d41d3faf/plugin/sleuth.vim#L44-51), but for backticks. Probably tighten the regex a bit because backticks are way more common than triple quotes.
