### ISSUE TITLE
There is no way to set ts=4

### ISSUE THREAD

**Issue by AjayChoudary** [tpope/vim-sleuth#64]
@tpope  Plugin is working awesome.
But default it is considering tab (\t) width to 8 for tab indent files, and there is no config provided to change it to 4. 
Currently I override it inside [plugin source](https://github.com/tpope/vim-sleuth/blob/master/plugin/sleuth.vim#L94).

We should have a configurable option to make ts=4 & sw=4

**Comment by zsugabubus** [comment]
[:mag:](https://github.com/tpope/vim-sleuth/issues?q=4)

**Comment by tpope** [comment]
This only happens when you mix tabs and spaces. This is to support files that deliberately use a tab to achieve a smaller file size. This was _very_ popular back in the day. Example: https://github.com/vim/vim/blob/c8a9fe541d3bee36d2760ed156997ddbb0142ee1/runtime/autoload/ada.vim#L230-L258

Further general purpose customization is likely coming in the near future. That 8 is staying hard coded until it arrives.

**Comment by tpope** [comment]
`'tabstop'` can now be set with a modeline or [EditorConfig](https://editorconfig.org/).

**Comment by unphased** [comment]
So this is a little off the beaten path but I do have a lot of scripts that I like to leave an extension off of. I like to keep my JS files at a tabstop of 2 instead of 4, but with the editorconfig rules 

    [*]
    end_of_line = lf
    insert_final_newline = true
    indent_style = space
    indent_size = 4
    charset = utf-8
    
    [*.{mjs,cjs,js,ts}]
    indent_size = 2

This does feel like there's simply no way without adding a filetype autocommand to override the tabstop because detecting a filetype is out of editorconfig's scope. Is this enough to argue for some form of language specific config support?

**Comment by tpope** [comment]
Is this self inflicted? Is there a reason you can't change the `[*]` to be more specific? Sounds like even `[*.*]` would solve your problem.

> Also, I thought the purpose of the extension is to use heuristics such as reading the buffer to determine the tabstop? Utilizing editorconfig is nice but ideally the heuristics should be robust enough and also made to take precedence over config by default.

The purpose of EditorConfig is to provide a mechanism more reliable than heuristics.

**Comment by tpope** [comment]
Also, is this `.editorconfig` in the root of a project? That's the intended use case, but it has occurred to me some people might attempt to use it in their home directory.

**Comment by unphased** [comment]
I think it's entirely fair to toss up the hands and stop trying to find heuristics for this purpose. Nothing's cropped up that actually works over the past 10 years so why keep looking. 

I have to explain. First: I was looking for this plugin to be able to work out if i open a 4-space-indented source file that it would be able to figure out to set ts=4 and expandtab. Well, I was going to play around and confirm that, but before I could, I saw that files that have enough tabs in them (like my .vimrc) got set to ts=8. Being allergic to ts=8, that simply would not do, and it seems .editorconfig is the only way to prevent ts=8 from ever being set. But... now editorconfig clobbers any of the subtly awesome behavior that the heuristics -- if present -- provide. Hope that explains my thought process. 

I'm not salty at all. It's just yet another one of those all too familiar confluences of all quite reasonable choices culminating in a suboptimal behavior.

I have confirmed it is picking up that config file properly. Even when the root of the project has no symlink to the one in my home dir. Presumably having one in the project would override the one in the home dir. This is fine. Perfect, even.

**Comment by tpope** [comment]
Okay, I recommend *against* using `.editorconfig` in your home directory, as it has exactly the downsides you have discovered.

> This does feel like there's simply no way without adding a filetype autocommand to override the tabstop because detecting a filetype is out of editorconfig's scope. Is this enough to argue for some form of language specific config support?

Indeed, I think there's a place here for filetype-specific config *instead* of the home directory `.editorconfig`. I completely restructured to use the filetype in 6121f40a49ad187c95aee71ca6cd00479618426c primarily to enable this. I haven't shipped it because I'm still working out how the precedence should work. For Ruby, for example, I want to be able to say "use `shiftwidth=2` always, don't even bother with heuristics", while with JavaScript, I want to be able to say "use shiftwidth=4, but only if we can't figure it out with heuristics". I want an interface that supports both and isn't too confusing. Hopefully it will ship soon.

> I have to explain. First: I was looking for this plugin to be able to work out if i open a 4-space-indented source file that it would be able to figure out to set ts=4 and expandtab.

If the file is indented with spaces, why do you care about `'tabstop'`? `'shiftwidth'` is the relevant option.

**Comment by unphased** [comment]
> If the file is indented with spaces, why do you care about `'tabstop'`? `'shiftwidth'` is the relevant option.

Thanks for the correction. 

> I want an interface that supports both and isn't too confusing. Hopefully it will ship soon.

This is spectacular to hear. Looking forward to it! I can probably just set up that autocommand and delete it later when it is released!

**Comment by tpope** [comment]
I think my endorsed solution here is going to be to put your default settings in `after/ftplugin/{filetype}.vim`. A configuration option just doesn't add that much on top of that. I thought it might help avoid load order issues, but I can't actually reproduce any load order issues with this approach. Sleuth appears to always trigger after the ftplugin, so we can override what's in it with our detected configuration.

I can reproduce load order issues with an `autocmd` in some edge cases, so I would softly encourage people to favor `after/ftplugin` over autocommands.

> For Ruby, for example, I want to be able to say "use `shiftwidth=2` always, don't even bother with heuristics"

For this I have added `let g:sleuth_ruby_heuristics = 0`. Or `let b:sleuth_heuristics = 0` in the `after/ftplugin` file if you want everything there.
