### ISSUE TITLE
Sets sw=6, ts=8 when file uses tabs

### ISSUE THREAD

**Issue by HaleTom** [tpope/vim-sleuth#65]
Here's the file:

https://raw.githubusercontent.com/git/git/master/git-add--interactive.perl

I was expecting `sw=4, ts=4` (preferred) or a least `sw=8, ts=8`.

**Comment by HaleTom** [comment]
Perhaps a user-settable variable to allow a person do define 2, 4, or 8 (etc) spaces as default if there are only TABs?

**Comment by sheerun** [comment]
vim-polyglot sets shiftwidth=0 if shiftwidth == tabstop (it makes shiftwidth to have the same value as tabstop by default) plus it doesn't change tabstop, so user can set favorite tabstop in .vimrc like so:

```
au FileType perl set tabstop=4
```

**Comment by HaleTom** [comment]
This may help detecting the causes in the provided file:

https://github.com/roryokane/detectindent/issues/18

**Comment by tpope** [comment]
We do respect `'tabstop''` if there are nothing but tabs. Unfortunately, there's a single line that starts with 6 spaces:

https://github.com/git/git/blob/abe6bb3905392d5eb6b01fa6e54d7e784e0522aa/git-add--interactive.perl#L481

I'm not seeing an obvious fix here. While a single line 6 space indent is almost certainly spurious, that's not very far from a sole pair of 4 space indents, which is valid:

```java
class MixedFile {
    public static void main(String[] args) {
	System.out.println("This file uses sw=4 ts=8 noet");
    }
}
```

Where do we draw the line?

I do have a fix coming for this particular example in the form of EditorConfig support. The repository in question has a `.editorconfig` with relevant settings:

```ini
[*.{c,h,sh,perl,pl,pm,txt}]
indent_style = tab
tab_width = 8
```

**Comment by tpope** [comment]
Looks like disallowing 6 as a valid indent level does allow it to detect this file as `shiftwidth=8 tabstop=8`, so I've gone ahead and done that. Unfortunately, this still won't allow `shiftwidth=0` like it would with a purely tab indented file.

Specifically, I changed the even number requirement to a multiple of 4 requirement, and given precedence to 4 and 8 over the uncommon (but still [occasionally used](https://github.com/exg/rxvt-unicode/blob/0ba94970e3c4466385bca169690082e6931897bf/src/perl/background) 3. I'm retaining support for large multiples of 4 because they have niche uses (e.g., I like `sw=24` in Vim help files) and I don't think I've had any error reports of that nature.

**Comment by HaleTom** [comment]
Thanks for resolving this! 🎉🥳
